CREATE TABLE IF NOT EXISTS "SHOPPINGCART"
(
    "ID"
    INTEGER
    PRIMARY
    KEY
    AUTO_INCREMENT,
    "USER"
    VARCHAR (50)
);


CREATE TABLE IF NOT EXISTS "SHOPPINGCART_BOOK"
(
    "ID"
    INTEGER
    PRIMARY
    KEY
    AUTO_INCREMENT,
    "BOOK_ID"
    int,
    "SHOPPINGCART_ID"
    int
);

ALTER TABLE SHOPPINGCART_BOOK add constraint FK_BOOK_ID FOREIGN Key (BOOK_ID) REFERENCES BOOK(ID);
ALTER TABLE SHOPPINGCART_BOOK add constraint FK_SHOPPINGCART_ID FOREIGN Key (SHOPPINGCART_ID) REFERENCES SHOPPINGCART(ID);


insert into SHOPPINGCART (USER) VALUES ('ConSol');
insert into SHOPPINGCART (USER) VALUES ('Conny');

insert into SHOPPINGCART_BOOK (BOOK_ID, SHOPPINGCART_ID) VALUES (1, 1);
insert into SHOPPINGCART_BOOK (BOOK_ID, SHOPPINGCART_ID) VALUES (2, 1);
insert into SHOPPINGCART_BOOK (BOOK_ID, SHOPPINGCART_ID) VALUES (1, 2);





